// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "jacobi2d_kernel_jacobi2d_kernel_entry118311.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic jacobi2d_kernel_jacobi2d_kernel_entry118311::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic jacobi2d_kernel_jacobi2d_kernel_entry118311::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> jacobi2d_kernel_jacobi2d_kernel_entry118311::ap_ST_fsm_state1 = "1";
const sc_lv<32> jacobi2d_kernel_jacobi2d_kernel_entry118311::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool jacobi2d_kernel_jacobi2d_kernel_entry118311::ap_const_boolean_1 = true;

jacobi2d_kernel_jacobi2d_kernel_entry118311::jacobi2d_kernel_jacobi2d_kernel_entry118311(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_coalesced_data_num_out1_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out1_full_n );

    SC_METHOD(thread_coalesced_data_num_out1_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_coalesced_data_num_out1_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_coalesced_data_num_out2_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out2_full_n );

    SC_METHOD(thread_coalesced_data_num_out2_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_coalesced_data_num_out2_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_coalesced_data_num_out3_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out3_full_n );

    SC_METHOD(thread_coalesced_data_num_out3_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_coalesced_data_num_out3_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_coalesced_data_num_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );

    SC_METHOD(thread_coalesced_data_num_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_coalesced_data_num_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_var_input_0_0_V_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( var_input_0_0_V_out_full_n );

    SC_METHOD(thread_var_input_0_0_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_input_0_0_V );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_input_0_0_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_input_0_1_V_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( var_input_0_1_V_out_full_n );

    SC_METHOD(thread_var_input_0_1_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_input_0_1_V );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_input_0_1_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_input_0_2_V_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( var_input_0_2_V_out_full_n );

    SC_METHOD(thread_var_input_0_2_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_input_0_2_V );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_input_0_2_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_input_0_3_V_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_input_0_3_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_input_0_3_V );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_input_0_3_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_output_0_0_V_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( var_output_0_0_V_out_full_n );

    SC_METHOD(thread_var_output_0_0_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_output_0_0_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_output_0_1_V_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( var_output_0_1_V_out_full_n );

    SC_METHOD(thread_var_output_0_1_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_1_V );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_output_0_1_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_output_0_2_V_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( var_output_0_2_V_out_full_n );

    SC_METHOD(thread_var_output_0_2_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_2_V );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_output_0_2_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_output_0_3_V_out_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( var_output_0_3_V_out_full_n );

    SC_METHOD(thread_var_output_0_3_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_3_V );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_var_output_0_3_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( coalesced_data_num_out_full_n );
    sensitive << ( coalesced_data_num_out1_full_n );
    sensitive << ( coalesced_data_num_out2_full_n );
    sensitive << ( coalesced_data_num_out3_full_n );
    sensitive << ( var_output_0_0_V_out_full_n );
    sensitive << ( var_output_0_1_V_out_full_n );
    sensitive << ( var_output_0_2_V_out_full_n );
    sensitive << ( var_output_0_3_V_out_full_n );
    sensitive << ( var_input_0_0_V_out_full_n );
    sensitive << ( var_input_0_1_V_out_full_n );
    sensitive << ( var_input_0_2_V_out_full_n );
    sensitive << ( var_input_0_3_V_out_full_n );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "jacobi2d_kernel_jacobi2d_kernel_entry118311_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, coalesced_data_num, "(port)coalesced_data_num");
    sc_trace(mVcdFile, coalesced_data_num_out_din, "(port)coalesced_data_num_out_din");
    sc_trace(mVcdFile, coalesced_data_num_out_full_n, "(port)coalesced_data_num_out_full_n");
    sc_trace(mVcdFile, coalesced_data_num_out_write, "(port)coalesced_data_num_out_write");
    sc_trace(mVcdFile, coalesced_data_num_out1_din, "(port)coalesced_data_num_out1_din");
    sc_trace(mVcdFile, coalesced_data_num_out1_full_n, "(port)coalesced_data_num_out1_full_n");
    sc_trace(mVcdFile, coalesced_data_num_out1_write, "(port)coalesced_data_num_out1_write");
    sc_trace(mVcdFile, coalesced_data_num_out2_din, "(port)coalesced_data_num_out2_din");
    sc_trace(mVcdFile, coalesced_data_num_out2_full_n, "(port)coalesced_data_num_out2_full_n");
    sc_trace(mVcdFile, coalesced_data_num_out2_write, "(port)coalesced_data_num_out2_write");
    sc_trace(mVcdFile, coalesced_data_num_out3_din, "(port)coalesced_data_num_out3_din");
    sc_trace(mVcdFile, coalesced_data_num_out3_full_n, "(port)coalesced_data_num_out3_full_n");
    sc_trace(mVcdFile, coalesced_data_num_out3_write, "(port)coalesced_data_num_out3_write");
    sc_trace(mVcdFile, var_output_0_0_V, "(port)var_output_0_0_V");
    sc_trace(mVcdFile, var_output_0_1_V, "(port)var_output_0_1_V");
    sc_trace(mVcdFile, var_output_0_2_V, "(port)var_output_0_2_V");
    sc_trace(mVcdFile, var_output_0_3_V, "(port)var_output_0_3_V");
    sc_trace(mVcdFile, var_input_0_0_V, "(port)var_input_0_0_V");
    sc_trace(mVcdFile, var_input_0_1_V, "(port)var_input_0_1_V");
    sc_trace(mVcdFile, var_input_0_2_V, "(port)var_input_0_2_V");
    sc_trace(mVcdFile, var_input_0_3_V, "(port)var_input_0_3_V");
    sc_trace(mVcdFile, var_output_0_0_V_out_din, "(port)var_output_0_0_V_out_din");
    sc_trace(mVcdFile, var_output_0_0_V_out_full_n, "(port)var_output_0_0_V_out_full_n");
    sc_trace(mVcdFile, var_output_0_0_V_out_write, "(port)var_output_0_0_V_out_write");
    sc_trace(mVcdFile, var_output_0_1_V_out_din, "(port)var_output_0_1_V_out_din");
    sc_trace(mVcdFile, var_output_0_1_V_out_full_n, "(port)var_output_0_1_V_out_full_n");
    sc_trace(mVcdFile, var_output_0_1_V_out_write, "(port)var_output_0_1_V_out_write");
    sc_trace(mVcdFile, var_output_0_2_V_out_din, "(port)var_output_0_2_V_out_din");
    sc_trace(mVcdFile, var_output_0_2_V_out_full_n, "(port)var_output_0_2_V_out_full_n");
    sc_trace(mVcdFile, var_output_0_2_V_out_write, "(port)var_output_0_2_V_out_write");
    sc_trace(mVcdFile, var_output_0_3_V_out_din, "(port)var_output_0_3_V_out_din");
    sc_trace(mVcdFile, var_output_0_3_V_out_full_n, "(port)var_output_0_3_V_out_full_n");
    sc_trace(mVcdFile, var_output_0_3_V_out_write, "(port)var_output_0_3_V_out_write");
    sc_trace(mVcdFile, var_input_0_0_V_out_din, "(port)var_input_0_0_V_out_din");
    sc_trace(mVcdFile, var_input_0_0_V_out_full_n, "(port)var_input_0_0_V_out_full_n");
    sc_trace(mVcdFile, var_input_0_0_V_out_write, "(port)var_input_0_0_V_out_write");
    sc_trace(mVcdFile, var_input_0_1_V_out_din, "(port)var_input_0_1_V_out_din");
    sc_trace(mVcdFile, var_input_0_1_V_out_full_n, "(port)var_input_0_1_V_out_full_n");
    sc_trace(mVcdFile, var_input_0_1_V_out_write, "(port)var_input_0_1_V_out_write");
    sc_trace(mVcdFile, var_input_0_2_V_out_din, "(port)var_input_0_2_V_out_din");
    sc_trace(mVcdFile, var_input_0_2_V_out_full_n, "(port)var_input_0_2_V_out_full_n");
    sc_trace(mVcdFile, var_input_0_2_V_out_write, "(port)var_input_0_2_V_out_write");
    sc_trace(mVcdFile, var_input_0_3_V_out_din, "(port)var_input_0_3_V_out_din");
    sc_trace(mVcdFile, var_input_0_3_V_out_full_n, "(port)var_input_0_3_V_out_full_n");
    sc_trace(mVcdFile, var_input_0_3_V_out_write, "(port)var_input_0_3_V_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, coalesced_data_num_out_blk_n, "coalesced_data_num_out_blk_n");
    sc_trace(mVcdFile, coalesced_data_num_out1_blk_n, "coalesced_data_num_out1_blk_n");
    sc_trace(mVcdFile, coalesced_data_num_out2_blk_n, "coalesced_data_num_out2_blk_n");
    sc_trace(mVcdFile, coalesced_data_num_out3_blk_n, "coalesced_data_num_out3_blk_n");
    sc_trace(mVcdFile, var_output_0_0_V_out_blk_n, "var_output_0_0_V_out_blk_n");
    sc_trace(mVcdFile, var_output_0_1_V_out_blk_n, "var_output_0_1_V_out_blk_n");
    sc_trace(mVcdFile, var_output_0_2_V_out_blk_n, "var_output_0_2_V_out_blk_n");
    sc_trace(mVcdFile, var_output_0_3_V_out_blk_n, "var_output_0_3_V_out_blk_n");
    sc_trace(mVcdFile, var_input_0_0_V_out_blk_n, "var_input_0_0_V_out_blk_n");
    sc_trace(mVcdFile, var_input_0_1_V_out_blk_n, "var_input_0_1_V_out_blk_n");
    sc_trace(mVcdFile, var_input_0_2_V_out_blk_n, "var_input_0_2_V_out_blk_n");
    sc_trace(mVcdFile, var_input_0_3_V_out_blk_n, "var_input_0_3_V_out_blk_n");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

jacobi2d_kernel_jacobi2d_kernel_entry118311::~jacobi2d_kernel_jacobi2d_kernel_entry118311() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_ap_done() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out1_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        coalesced_data_num_out1_blk_n = coalesced_data_num_out1_full_n.read();
    } else {
        coalesced_data_num_out1_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out1_din() {
    coalesced_data_num_out1_din = coalesced_data_num.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out1_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        coalesced_data_num_out1_write = ap_const_logic_1;
    } else {
        coalesced_data_num_out1_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out2_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        coalesced_data_num_out2_blk_n = coalesced_data_num_out2_full_n.read();
    } else {
        coalesced_data_num_out2_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out2_din() {
    coalesced_data_num_out2_din = coalesced_data_num.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out2_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        coalesced_data_num_out2_write = ap_const_logic_1;
    } else {
        coalesced_data_num_out2_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out3_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        coalesced_data_num_out3_blk_n = coalesced_data_num_out3_full_n.read();
    } else {
        coalesced_data_num_out3_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out3_din() {
    coalesced_data_num_out3_din = coalesced_data_num.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out3_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        coalesced_data_num_out3_write = ap_const_logic_1;
    } else {
        coalesced_data_num_out3_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        coalesced_data_num_out_blk_n = coalesced_data_num_out_full_n.read();
    } else {
        coalesced_data_num_out_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out_din() {
    coalesced_data_num_out_din = coalesced_data_num.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_coalesced_data_num_out_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        coalesced_data_num_out_write = ap_const_logic_1;
    } else {
        coalesced_data_num_out_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_internal_ap_ready() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_start_out() {
    start_out = real_start.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_0_V_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        var_input_0_0_V_out_blk_n = var_input_0_0_V_out_full_n.read();
    } else {
        var_input_0_0_V_out_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_0_V_out_din() {
    var_input_0_0_V_out_din = var_input_0_0_V.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_0_V_out_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        var_input_0_0_V_out_write = ap_const_logic_1;
    } else {
        var_input_0_0_V_out_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_1_V_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        var_input_0_1_V_out_blk_n = var_input_0_1_V_out_full_n.read();
    } else {
        var_input_0_1_V_out_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_1_V_out_din() {
    var_input_0_1_V_out_din = var_input_0_1_V.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_1_V_out_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        var_input_0_1_V_out_write = ap_const_logic_1;
    } else {
        var_input_0_1_V_out_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_2_V_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        var_input_0_2_V_out_blk_n = var_input_0_2_V_out_full_n.read();
    } else {
        var_input_0_2_V_out_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_2_V_out_din() {
    var_input_0_2_V_out_din = var_input_0_2_V.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_2_V_out_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        var_input_0_2_V_out_write = ap_const_logic_1;
    } else {
        var_input_0_2_V_out_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_3_V_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        var_input_0_3_V_out_blk_n = var_input_0_3_V_out_full_n.read();
    } else {
        var_input_0_3_V_out_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_3_V_out_din() {
    var_input_0_3_V_out_din = var_input_0_3_V.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_input_0_3_V_out_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        var_input_0_3_V_out_write = ap_const_logic_1;
    } else {
        var_input_0_3_V_out_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_0_V_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        var_output_0_0_V_out_blk_n = var_output_0_0_V_out_full_n.read();
    } else {
        var_output_0_0_V_out_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_0_V_out_din() {
    var_output_0_0_V_out_din = var_output_0_0_V.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_0_V_out_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        var_output_0_0_V_out_write = ap_const_logic_1;
    } else {
        var_output_0_0_V_out_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_1_V_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        var_output_0_1_V_out_blk_n = var_output_0_1_V_out_full_n.read();
    } else {
        var_output_0_1_V_out_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_1_V_out_din() {
    var_output_0_1_V_out_din = var_output_0_1_V.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_1_V_out_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        var_output_0_1_V_out_write = ap_const_logic_1;
    } else {
        var_output_0_1_V_out_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_2_V_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        var_output_0_2_V_out_blk_n = var_output_0_2_V_out_full_n.read();
    } else {
        var_output_0_2_V_out_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_2_V_out_din() {
    var_output_0_2_V_out_din = var_output_0_2_V.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_2_V_out_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        var_output_0_2_V_out_write = ap_const_logic_1;
    } else {
        var_output_0_2_V_out_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_3_V_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        var_output_0_3_V_out_blk_n = var_output_0_3_V_out_full_n.read();
    } else {
        var_output_0_3_V_out_blk_n = ap_const_logic_1;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_3_V_out_din() {
    var_output_0_3_V_out_din = var_output_0_3_V.read();
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_var_output_0_3_V_out_write() {
    if ((!(esl_seteq<1,1,1>(var_input_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_input_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_3_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_2_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_1_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(var_output_0_0_V_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out3_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(coalesced_data_num_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        var_output_0_3_V_out_write = ap_const_logic_1;
    } else {
        var_output_0_3_V_out_write = ap_const_logic_0;
    }
}

void jacobi2d_kernel_jacobi2d_kernel_entry118311::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

