// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module jacobi2d_kernel_jacobi2d_kernel_entry118311 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        coalesced_data_num,
        coalesced_data_num_out_din,
        coalesced_data_num_out_full_n,
        coalesced_data_num_out_write,
        coalesced_data_num_out1_din,
        coalesced_data_num_out1_full_n,
        coalesced_data_num_out1_write,
        coalesced_data_num_out2_din,
        coalesced_data_num_out2_full_n,
        coalesced_data_num_out2_write,
        coalesced_data_num_out3_din,
        coalesced_data_num_out3_full_n,
        coalesced_data_num_out3_write,
        var_output_0_0_V,
        var_output_0_1_V,
        var_output_0_2_V,
        var_output_0_3_V,
        var_input_0_0_V,
        var_input_0_1_V,
        var_input_0_2_V,
        var_input_0_3_V,
        var_output_0_0_V_out_din,
        var_output_0_0_V_out_full_n,
        var_output_0_0_V_out_write,
        var_output_0_1_V_out_din,
        var_output_0_1_V_out_full_n,
        var_output_0_1_V_out_write,
        var_output_0_2_V_out_din,
        var_output_0_2_V_out_full_n,
        var_output_0_2_V_out_write,
        var_output_0_3_V_out_din,
        var_output_0_3_V_out_full_n,
        var_output_0_3_V_out_write,
        var_input_0_0_V_out_din,
        var_input_0_0_V_out_full_n,
        var_input_0_0_V_out_write,
        var_input_0_1_V_out_din,
        var_input_0_1_V_out_full_n,
        var_input_0_1_V_out_write,
        var_input_0_2_V_out_din,
        var_input_0_2_V_out_full_n,
        var_input_0_2_V_out_write,
        var_input_0_3_V_out_din,
        var_input_0_3_V_out_full_n,
        var_input_0_3_V_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] coalesced_data_num;
output  [63:0] coalesced_data_num_out_din;
input   coalesced_data_num_out_full_n;
output   coalesced_data_num_out_write;
output  [63:0] coalesced_data_num_out1_din;
input   coalesced_data_num_out1_full_n;
output   coalesced_data_num_out1_write;
output  [63:0] coalesced_data_num_out2_din;
input   coalesced_data_num_out2_full_n;
output   coalesced_data_num_out2_write;
output  [63:0] coalesced_data_num_out3_din;
input   coalesced_data_num_out3_full_n;
output   coalesced_data_num_out3_write;
input  [31:0] var_output_0_0_V;
input  [31:0] var_output_0_1_V;
input  [31:0] var_output_0_2_V;
input  [31:0] var_output_0_3_V;
input  [31:0] var_input_0_0_V;
input  [31:0] var_input_0_1_V;
input  [31:0] var_input_0_2_V;
input  [31:0] var_input_0_3_V;
output  [31:0] var_output_0_0_V_out_din;
input   var_output_0_0_V_out_full_n;
output   var_output_0_0_V_out_write;
output  [31:0] var_output_0_1_V_out_din;
input   var_output_0_1_V_out_full_n;
output   var_output_0_1_V_out_write;
output  [31:0] var_output_0_2_V_out_din;
input   var_output_0_2_V_out_full_n;
output   var_output_0_2_V_out_write;
output  [31:0] var_output_0_3_V_out_din;
input   var_output_0_3_V_out_full_n;
output   var_output_0_3_V_out_write;
output  [31:0] var_input_0_0_V_out_din;
input   var_input_0_0_V_out_full_n;
output   var_input_0_0_V_out_write;
output  [31:0] var_input_0_1_V_out_din;
input   var_input_0_1_V_out_full_n;
output   var_input_0_1_V_out_write;
output  [31:0] var_input_0_2_V_out_din;
input   var_input_0_2_V_out_full_n;
output   var_input_0_2_V_out_write;
output  [31:0] var_input_0_3_V_out_din;
input   var_input_0_3_V_out_full_n;
output   var_input_0_3_V_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg coalesced_data_num_out_write;
reg coalesced_data_num_out1_write;
reg coalesced_data_num_out2_write;
reg coalesced_data_num_out3_write;
reg var_output_0_0_V_out_write;
reg var_output_0_1_V_out_write;
reg var_output_0_2_V_out_write;
reg var_output_0_3_V_out_write;
reg var_input_0_0_V_out_write;
reg var_input_0_1_V_out_write;
reg var_input_0_2_V_out_write;
reg var_input_0_3_V_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    coalesced_data_num_out_blk_n;
reg    coalesced_data_num_out1_blk_n;
reg    coalesced_data_num_out2_blk_n;
reg    coalesced_data_num_out3_blk_n;
reg    var_output_0_0_V_out_blk_n;
reg    var_output_0_1_V_out_blk_n;
reg    var_output_0_2_V_out_blk_n;
reg    var_output_0_3_V_out_blk_n;
reg    var_input_0_0_V_out_blk_n;
reg    var_input_0_1_V_out_blk_n;
reg    var_input_0_2_V_out_blk_n;
reg    var_input_0_3_V_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        coalesced_data_num_out1_blk_n = coalesced_data_num_out1_full_n;
    end else begin
        coalesced_data_num_out1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        coalesced_data_num_out1_write = 1'b1;
    end else begin
        coalesced_data_num_out1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        coalesced_data_num_out2_blk_n = coalesced_data_num_out2_full_n;
    end else begin
        coalesced_data_num_out2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        coalesced_data_num_out2_write = 1'b1;
    end else begin
        coalesced_data_num_out2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        coalesced_data_num_out3_blk_n = coalesced_data_num_out3_full_n;
    end else begin
        coalesced_data_num_out3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        coalesced_data_num_out3_write = 1'b1;
    end else begin
        coalesced_data_num_out3_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        coalesced_data_num_out_blk_n = coalesced_data_num_out_full_n;
    end else begin
        coalesced_data_num_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        coalesced_data_num_out_write = 1'b1;
    end else begin
        coalesced_data_num_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        var_input_0_0_V_out_blk_n = var_input_0_0_V_out_full_n;
    end else begin
        var_input_0_0_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        var_input_0_0_V_out_write = 1'b1;
    end else begin
        var_input_0_0_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        var_input_0_1_V_out_blk_n = var_input_0_1_V_out_full_n;
    end else begin
        var_input_0_1_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        var_input_0_1_V_out_write = 1'b1;
    end else begin
        var_input_0_1_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        var_input_0_2_V_out_blk_n = var_input_0_2_V_out_full_n;
    end else begin
        var_input_0_2_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        var_input_0_2_V_out_write = 1'b1;
    end else begin
        var_input_0_2_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        var_input_0_3_V_out_blk_n = var_input_0_3_V_out_full_n;
    end else begin
        var_input_0_3_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        var_input_0_3_V_out_write = 1'b1;
    end else begin
        var_input_0_3_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        var_output_0_0_V_out_blk_n = var_output_0_0_V_out_full_n;
    end else begin
        var_output_0_0_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        var_output_0_0_V_out_write = 1'b1;
    end else begin
        var_output_0_0_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        var_output_0_1_V_out_blk_n = var_output_0_1_V_out_full_n;
    end else begin
        var_output_0_1_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        var_output_0_1_V_out_write = 1'b1;
    end else begin
        var_output_0_1_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        var_output_0_2_V_out_blk_n = var_output_0_2_V_out_full_n;
    end else begin
        var_output_0_2_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        var_output_0_2_V_out_write = 1'b1;
    end else begin
        var_output_0_2_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        var_output_0_3_V_out_blk_n = var_output_0_3_V_out_full_n;
    end else begin
        var_output_0_3_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        var_output_0_3_V_out_write = 1'b1;
    end else begin
        var_output_0_3_V_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((var_input_0_3_V_out_full_n == 1'b0) | (var_input_0_2_V_out_full_n == 1'b0) | (var_input_0_1_V_out_full_n == 1'b0) | (var_input_0_0_V_out_full_n == 1'b0) | (var_output_0_3_V_out_full_n == 1'b0) | (var_output_0_2_V_out_full_n == 1'b0) | (real_start == 1'b0) | (var_output_0_1_V_out_full_n == 1'b0) | (var_output_0_0_V_out_full_n == 1'b0) | (coalesced_data_num_out3_full_n == 1'b0) | (coalesced_data_num_out2_full_n == 1'b0) | (coalesced_data_num_out1_full_n == 1'b0) | (coalesced_data_num_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign coalesced_data_num_out1_din = coalesced_data_num;

assign coalesced_data_num_out2_din = coalesced_data_num;

assign coalesced_data_num_out3_din = coalesced_data_num;

assign coalesced_data_num_out_din = coalesced_data_num;

assign start_out = real_start;

assign var_input_0_0_V_out_din = var_input_0_0_V;

assign var_input_0_1_V_out_din = var_input_0_1_V;

assign var_input_0_2_V_out_din = var_input_0_2_V;

assign var_input_0_3_V_out_din = var_input_0_3_V;

assign var_output_0_0_V_out_din = var_output_0_0_V;

assign var_output_0_1_V_out_din = var_output_0_1_V;

assign var_output_0_2_V_out_din = var_output_0_2_V;

assign var_output_0_3_V_out_din = var_output_0_3_V;

endmodule //jacobi2d_kernel_jacobi2d_kernel_entry118311
