// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module buffer_load (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        flag,
        local_buf_0_V_address0,
        local_buf_0_V_ce0,
        local_buf_0_V_we0,
        local_buf_0_V_d0,
        local_buf_1_V_address0,
        local_buf_1_V_ce0,
        local_buf_1_V_we0,
        local_buf_1_V_d0,
        local_buf_2_V_address0,
        local_buf_2_V_ce0,
        local_buf_2_V_we0,
        local_buf_2_V_d0,
        local_buf_3_V_address0,
        local_buf_3_V_ce0,
        local_buf_3_V_we0,
        local_buf_3_V_d0,
        local_buf_4_V_address0,
        local_buf_4_V_ce0,
        local_buf_4_V_we0,
        local_buf_4_V_d0,
        local_buf_5_V_address0,
        local_buf_5_V_ce0,
        local_buf_5_V_we0,
        local_buf_5_V_d0,
        local_buf_6_V_address0,
        local_buf_6_V_ce0,
        local_buf_6_V_we0,
        local_buf_6_V_d0,
        local_buf_7_V_address0,
        local_buf_7_V_ce0,
        local_buf_7_V_we0,
        local_buf_7_V_d0,
        local_buf_8_V_address0,
        local_buf_8_V_ce0,
        local_buf_8_V_we0,
        local_buf_8_V_d0,
        local_buf_9_V_address0,
        local_buf_9_V_ce0,
        local_buf_9_V_we0,
        local_buf_9_V_d0,
        local_buf_10_V_address0,
        local_buf_10_V_ce0,
        local_buf_10_V_we0,
        local_buf_10_V_d0,
        local_buf_11_V_address0,
        local_buf_11_V_ce0,
        local_buf_11_V_we0,
        local_buf_11_V_d0,
        local_buf_12_V_address0,
        local_buf_12_V_ce0,
        local_buf_12_V_we0,
        local_buf_12_V_d0,
        local_buf_13_V_address0,
        local_buf_13_V_ce0,
        local_buf_13_V_we0,
        local_buf_13_V_d0,
        local_buf_14_V_address0,
        local_buf_14_V_ce0,
        local_buf_14_V_we0,
        local_buf_14_V_d0,
        local_buf_15_V_address0,
        local_buf_15_V_ce0,
        local_buf_15_V_we0,
        local_buf_15_V_d0,
        local_buf_16_V_address0,
        local_buf_16_V_ce0,
        local_buf_16_V_we0,
        local_buf_16_V_d0,
        local_buf_17_V_address0,
        local_buf_17_V_ce0,
        local_buf_17_V_we0,
        local_buf_17_V_d0,
        local_buf_18_V_address0,
        local_buf_18_V_ce0,
        local_buf_18_V_we0,
        local_buf_18_V_d0,
        local_buf_19_V_address0,
        local_buf_19_V_ce0,
        local_buf_19_V_we0,
        local_buf_19_V_d0,
        local_buf_20_V_address0,
        local_buf_20_V_ce0,
        local_buf_20_V_we0,
        local_buf_20_V_d0,
        local_buf_21_V_address0,
        local_buf_21_V_ce0,
        local_buf_21_V_we0,
        local_buf_21_V_d0,
        local_buf_22_V_address0,
        local_buf_22_V_ce0,
        local_buf_22_V_we0,
        local_buf_22_V_d0,
        local_buf_23_V_address0,
        local_buf_23_V_ce0,
        local_buf_23_V_we0,
        local_buf_23_V_d0,
        local_buf_24_V_address0,
        local_buf_24_V_ce0,
        local_buf_24_V_we0,
        local_buf_24_V_d0,
        local_buf_25_V_address0,
        local_buf_25_V_ce0,
        local_buf_25_V_we0,
        local_buf_25_V_d0,
        local_buf_26_V_address0,
        local_buf_26_V_ce0,
        local_buf_26_V_we0,
        local_buf_26_V_d0,
        local_buf_27_V_address0,
        local_buf_27_V_ce0,
        local_buf_27_V_we0,
        local_buf_27_V_d0,
        local_buf_28_V_address0,
        local_buf_28_V_ce0,
        local_buf_28_V_we0,
        local_buf_28_V_d0,
        local_buf_29_V_address0,
        local_buf_29_V_ce0,
        local_buf_29_V_we0,
        local_buf_29_V_d0,
        local_buf_30_V_address0,
        local_buf_30_V_ce0,
        local_buf_30_V_we0,
        local_buf_30_V_d0,
        local_buf_31_V_address0,
        local_buf_31_V_ce0,
        local_buf_31_V_we0,
        local_buf_31_V_d0,
        local_buf_32_V_address0,
        local_buf_32_V_ce0,
        local_buf_32_V_we0,
        local_buf_32_V_d0,
        local_buf_33_V_address0,
        local_buf_33_V_ce0,
        local_buf_33_V_we0,
        local_buf_33_V_d0,
        local_buf_34_V_address0,
        local_buf_34_V_ce0,
        local_buf_34_V_we0,
        local_buf_34_V_d0,
        local_buf_35_V_address0,
        local_buf_35_V_ce0,
        local_buf_35_V_we0,
        local_buf_35_V_d0,
        local_buf_36_V_address0,
        local_buf_36_V_ce0,
        local_buf_36_V_we0,
        local_buf_36_V_d0,
        local_buf_37_V_address0,
        local_buf_37_V_ce0,
        local_buf_37_V_we0,
        local_buf_37_V_d0,
        local_buf_38_V_address0,
        local_buf_38_V_ce0,
        local_buf_38_V_we0,
        local_buf_38_V_d0,
        local_buf_39_V_address0,
        local_buf_39_V_ce0,
        local_buf_39_V_we0,
        local_buf_39_V_d0,
        local_buf_40_V_address0,
        local_buf_40_V_ce0,
        local_buf_40_V_we0,
        local_buf_40_V_d0,
        local_buf_41_V_address0,
        local_buf_41_V_ce0,
        local_buf_41_V_we0,
        local_buf_41_V_d0,
        local_buf_42_V_address0,
        local_buf_42_V_ce0,
        local_buf_42_V_we0,
        local_buf_42_V_d0,
        local_buf_43_V_address0,
        local_buf_43_V_ce0,
        local_buf_43_V_we0,
        local_buf_43_V_d0,
        local_buf_44_V_address0,
        local_buf_44_V_ce0,
        local_buf_44_V_we0,
        local_buf_44_V_d0,
        local_buf_45_V_address0,
        local_buf_45_V_ce0,
        local_buf_45_V_we0,
        local_buf_45_V_d0,
        local_buf_46_V_address0,
        local_buf_46_V_ce0,
        local_buf_46_V_we0,
        local_buf_46_V_d0,
        local_buf_47_V_address0,
        local_buf_47_V_ce0,
        local_buf_47_V_we0,
        local_buf_47_V_d0,
        local_buf_48_V_address0,
        local_buf_48_V_ce0,
        local_buf_48_V_we0,
        local_buf_48_V_d0,
        local_buf_49_V_address0,
        local_buf_49_V_ce0,
        local_buf_49_V_we0,
        local_buf_49_V_d0,
        local_buf_50_V_address0,
        local_buf_50_V_ce0,
        local_buf_50_V_we0,
        local_buf_50_V_d0,
        local_buf_51_V_address0,
        local_buf_51_V_ce0,
        local_buf_51_V_we0,
        local_buf_51_V_d0,
        local_buf_52_V_address0,
        local_buf_52_V_ce0,
        local_buf_52_V_we0,
        local_buf_52_V_d0,
        local_buf_53_V_address0,
        local_buf_53_V_ce0,
        local_buf_53_V_we0,
        local_buf_53_V_d0,
        local_buf_54_V_address0,
        local_buf_54_V_ce0,
        local_buf_54_V_we0,
        local_buf_54_V_d0,
        local_buf_55_V_address0,
        local_buf_55_V_ce0,
        local_buf_55_V_we0,
        local_buf_55_V_d0,
        local_buf_56_V_address0,
        local_buf_56_V_ce0,
        local_buf_56_V_we0,
        local_buf_56_V_d0,
        local_buf_57_V_address0,
        local_buf_57_V_ce0,
        local_buf_57_V_we0,
        local_buf_57_V_d0,
        local_buf_58_V_address0,
        local_buf_58_V_ce0,
        local_buf_58_V_we0,
        local_buf_58_V_d0,
        local_buf_59_V_address0,
        local_buf_59_V_ce0,
        local_buf_59_V_we0,
        local_buf_59_V_d0,
        local_buf_60_V_address0,
        local_buf_60_V_ce0,
        local_buf_60_V_we0,
        local_buf_60_V_d0,
        local_buf_61_V_address0,
        local_buf_61_V_ce0,
        local_buf_61_V_we0,
        local_buf_61_V_d0,
        local_buf_62_V_address0,
        local_buf_62_V_ce0,
        local_buf_62_V_we0,
        local_buf_62_V_d0,
        local_buf_63_V_address0,
        local_buf_63_V_ce0,
        local_buf_63_V_we0,
        local_buf_63_V_d0,
        m_axi_global_buf_V_AWVALID,
        m_axi_global_buf_V_AWREADY,
        m_axi_global_buf_V_AWADDR,
        m_axi_global_buf_V_AWID,
        m_axi_global_buf_V_AWLEN,
        m_axi_global_buf_V_AWSIZE,
        m_axi_global_buf_V_AWBURST,
        m_axi_global_buf_V_AWLOCK,
        m_axi_global_buf_V_AWCACHE,
        m_axi_global_buf_V_AWPROT,
        m_axi_global_buf_V_AWQOS,
        m_axi_global_buf_V_AWREGION,
        m_axi_global_buf_V_AWUSER,
        m_axi_global_buf_V_WVALID,
        m_axi_global_buf_V_WREADY,
        m_axi_global_buf_V_WDATA,
        m_axi_global_buf_V_WSTRB,
        m_axi_global_buf_V_WLAST,
        m_axi_global_buf_V_WID,
        m_axi_global_buf_V_WUSER,
        m_axi_global_buf_V_ARVALID,
        m_axi_global_buf_V_ARREADY,
        m_axi_global_buf_V_ARADDR,
        m_axi_global_buf_V_ARID,
        m_axi_global_buf_V_ARLEN,
        m_axi_global_buf_V_ARSIZE,
        m_axi_global_buf_V_ARBURST,
        m_axi_global_buf_V_ARLOCK,
        m_axi_global_buf_V_ARCACHE,
        m_axi_global_buf_V_ARPROT,
        m_axi_global_buf_V_ARQOS,
        m_axi_global_buf_V_ARREGION,
        m_axi_global_buf_V_ARUSER,
        m_axi_global_buf_V_RVALID,
        m_axi_global_buf_V_RREADY,
        m_axi_global_buf_V_RDATA,
        m_axi_global_buf_V_RLAST,
        m_axi_global_buf_V_RID,
        m_axi_global_buf_V_RUSER,
        m_axi_global_buf_V_RRESP,
        m_axi_global_buf_V_BVALID,
        m_axi_global_buf_V_BREADY,
        m_axi_global_buf_V_BRESP,
        m_axi_global_buf_V_BID,
        m_axi_global_buf_V_BUSER,
        global_buf_V_offset,
        global_buf_V_offset1
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_pp0_stage0 = 10'd256;
parameter    ap_ST_fsm_state12 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   flag;
output  [5:0] local_buf_0_V_address0;
output   local_buf_0_V_ce0;
output   local_buf_0_V_we0;
output  [511:0] local_buf_0_V_d0;
output  [5:0] local_buf_1_V_address0;
output   local_buf_1_V_ce0;
output   local_buf_1_V_we0;
output  [511:0] local_buf_1_V_d0;
output  [5:0] local_buf_2_V_address0;
output   local_buf_2_V_ce0;
output   local_buf_2_V_we0;
output  [511:0] local_buf_2_V_d0;
output  [5:0] local_buf_3_V_address0;
output   local_buf_3_V_ce0;
output   local_buf_3_V_we0;
output  [511:0] local_buf_3_V_d0;
output  [5:0] local_buf_4_V_address0;
output   local_buf_4_V_ce0;
output   local_buf_4_V_we0;
output  [511:0] local_buf_4_V_d0;
output  [5:0] local_buf_5_V_address0;
output   local_buf_5_V_ce0;
output   local_buf_5_V_we0;
output  [511:0] local_buf_5_V_d0;
output  [5:0] local_buf_6_V_address0;
output   local_buf_6_V_ce0;
output   local_buf_6_V_we0;
output  [511:0] local_buf_6_V_d0;
output  [5:0] local_buf_7_V_address0;
output   local_buf_7_V_ce0;
output   local_buf_7_V_we0;
output  [511:0] local_buf_7_V_d0;
output  [5:0] local_buf_8_V_address0;
output   local_buf_8_V_ce0;
output   local_buf_8_V_we0;
output  [511:0] local_buf_8_V_d0;
output  [5:0] local_buf_9_V_address0;
output   local_buf_9_V_ce0;
output   local_buf_9_V_we0;
output  [511:0] local_buf_9_V_d0;
output  [5:0] local_buf_10_V_address0;
output   local_buf_10_V_ce0;
output   local_buf_10_V_we0;
output  [511:0] local_buf_10_V_d0;
output  [5:0] local_buf_11_V_address0;
output   local_buf_11_V_ce0;
output   local_buf_11_V_we0;
output  [511:0] local_buf_11_V_d0;
output  [5:0] local_buf_12_V_address0;
output   local_buf_12_V_ce0;
output   local_buf_12_V_we0;
output  [511:0] local_buf_12_V_d0;
output  [5:0] local_buf_13_V_address0;
output   local_buf_13_V_ce0;
output   local_buf_13_V_we0;
output  [511:0] local_buf_13_V_d0;
output  [5:0] local_buf_14_V_address0;
output   local_buf_14_V_ce0;
output   local_buf_14_V_we0;
output  [511:0] local_buf_14_V_d0;
output  [5:0] local_buf_15_V_address0;
output   local_buf_15_V_ce0;
output   local_buf_15_V_we0;
output  [511:0] local_buf_15_V_d0;
output  [5:0] local_buf_16_V_address0;
output   local_buf_16_V_ce0;
output   local_buf_16_V_we0;
output  [511:0] local_buf_16_V_d0;
output  [5:0] local_buf_17_V_address0;
output   local_buf_17_V_ce0;
output   local_buf_17_V_we0;
output  [511:0] local_buf_17_V_d0;
output  [5:0] local_buf_18_V_address0;
output   local_buf_18_V_ce0;
output   local_buf_18_V_we0;
output  [511:0] local_buf_18_V_d0;
output  [5:0] local_buf_19_V_address0;
output   local_buf_19_V_ce0;
output   local_buf_19_V_we0;
output  [511:0] local_buf_19_V_d0;
output  [5:0] local_buf_20_V_address0;
output   local_buf_20_V_ce0;
output   local_buf_20_V_we0;
output  [511:0] local_buf_20_V_d0;
output  [5:0] local_buf_21_V_address0;
output   local_buf_21_V_ce0;
output   local_buf_21_V_we0;
output  [511:0] local_buf_21_V_d0;
output  [5:0] local_buf_22_V_address0;
output   local_buf_22_V_ce0;
output   local_buf_22_V_we0;
output  [511:0] local_buf_22_V_d0;
output  [5:0] local_buf_23_V_address0;
output   local_buf_23_V_ce0;
output   local_buf_23_V_we0;
output  [511:0] local_buf_23_V_d0;
output  [5:0] local_buf_24_V_address0;
output   local_buf_24_V_ce0;
output   local_buf_24_V_we0;
output  [511:0] local_buf_24_V_d0;
output  [5:0] local_buf_25_V_address0;
output   local_buf_25_V_ce0;
output   local_buf_25_V_we0;
output  [511:0] local_buf_25_V_d0;
output  [5:0] local_buf_26_V_address0;
output   local_buf_26_V_ce0;
output   local_buf_26_V_we0;
output  [511:0] local_buf_26_V_d0;
output  [5:0] local_buf_27_V_address0;
output   local_buf_27_V_ce0;
output   local_buf_27_V_we0;
output  [511:0] local_buf_27_V_d0;
output  [5:0] local_buf_28_V_address0;
output   local_buf_28_V_ce0;
output   local_buf_28_V_we0;
output  [511:0] local_buf_28_V_d0;
output  [5:0] local_buf_29_V_address0;
output   local_buf_29_V_ce0;
output   local_buf_29_V_we0;
output  [511:0] local_buf_29_V_d0;
output  [5:0] local_buf_30_V_address0;
output   local_buf_30_V_ce0;
output   local_buf_30_V_we0;
output  [511:0] local_buf_30_V_d0;
output  [5:0] local_buf_31_V_address0;
output   local_buf_31_V_ce0;
output   local_buf_31_V_we0;
output  [511:0] local_buf_31_V_d0;
output  [5:0] local_buf_32_V_address0;
output   local_buf_32_V_ce0;
output   local_buf_32_V_we0;
output  [511:0] local_buf_32_V_d0;
output  [5:0] local_buf_33_V_address0;
output   local_buf_33_V_ce0;
output   local_buf_33_V_we0;
output  [511:0] local_buf_33_V_d0;
output  [5:0] local_buf_34_V_address0;
output   local_buf_34_V_ce0;
output   local_buf_34_V_we0;
output  [511:0] local_buf_34_V_d0;
output  [5:0] local_buf_35_V_address0;
output   local_buf_35_V_ce0;
output   local_buf_35_V_we0;
output  [511:0] local_buf_35_V_d0;
output  [5:0] local_buf_36_V_address0;
output   local_buf_36_V_ce0;
output   local_buf_36_V_we0;
output  [511:0] local_buf_36_V_d0;
output  [5:0] local_buf_37_V_address0;
output   local_buf_37_V_ce0;
output   local_buf_37_V_we0;
output  [511:0] local_buf_37_V_d0;
output  [5:0] local_buf_38_V_address0;
output   local_buf_38_V_ce0;
output   local_buf_38_V_we0;
output  [511:0] local_buf_38_V_d0;
output  [5:0] local_buf_39_V_address0;
output   local_buf_39_V_ce0;
output   local_buf_39_V_we0;
output  [511:0] local_buf_39_V_d0;
output  [5:0] local_buf_40_V_address0;
output   local_buf_40_V_ce0;
output   local_buf_40_V_we0;
output  [511:0] local_buf_40_V_d0;
output  [5:0] local_buf_41_V_address0;
output   local_buf_41_V_ce0;
output   local_buf_41_V_we0;
output  [511:0] local_buf_41_V_d0;
output  [5:0] local_buf_42_V_address0;
output   local_buf_42_V_ce0;
output   local_buf_42_V_we0;
output  [511:0] local_buf_42_V_d0;
output  [5:0] local_buf_43_V_address0;
output   local_buf_43_V_ce0;
output   local_buf_43_V_we0;
output  [511:0] local_buf_43_V_d0;
output  [5:0] local_buf_44_V_address0;
output   local_buf_44_V_ce0;
output   local_buf_44_V_we0;
output  [511:0] local_buf_44_V_d0;
output  [5:0] local_buf_45_V_address0;
output   local_buf_45_V_ce0;
output   local_buf_45_V_we0;
output  [511:0] local_buf_45_V_d0;
output  [5:0] local_buf_46_V_address0;
output   local_buf_46_V_ce0;
output   local_buf_46_V_we0;
output  [511:0] local_buf_46_V_d0;
output  [5:0] local_buf_47_V_address0;
output   local_buf_47_V_ce0;
output   local_buf_47_V_we0;
output  [511:0] local_buf_47_V_d0;
output  [5:0] local_buf_48_V_address0;
output   local_buf_48_V_ce0;
output   local_buf_48_V_we0;
output  [511:0] local_buf_48_V_d0;
output  [5:0] local_buf_49_V_address0;
output   local_buf_49_V_ce0;
output   local_buf_49_V_we0;
output  [511:0] local_buf_49_V_d0;
output  [5:0] local_buf_50_V_address0;
output   local_buf_50_V_ce0;
output   local_buf_50_V_we0;
output  [511:0] local_buf_50_V_d0;
output  [5:0] local_buf_51_V_address0;
output   local_buf_51_V_ce0;
output   local_buf_51_V_we0;
output  [511:0] local_buf_51_V_d0;
output  [5:0] local_buf_52_V_address0;
output   local_buf_52_V_ce0;
output   local_buf_52_V_we0;
output  [511:0] local_buf_52_V_d0;
output  [5:0] local_buf_53_V_address0;
output   local_buf_53_V_ce0;
output   local_buf_53_V_we0;
output  [511:0] local_buf_53_V_d0;
output  [5:0] local_buf_54_V_address0;
output   local_buf_54_V_ce0;
output   local_buf_54_V_we0;
output  [511:0] local_buf_54_V_d0;
output  [5:0] local_buf_55_V_address0;
output   local_buf_55_V_ce0;
output   local_buf_55_V_we0;
output  [511:0] local_buf_55_V_d0;
output  [5:0] local_buf_56_V_address0;
output   local_buf_56_V_ce0;
output   local_buf_56_V_we0;
output  [511:0] local_buf_56_V_d0;
output  [5:0] local_buf_57_V_address0;
output   local_buf_57_V_ce0;
output   local_buf_57_V_we0;
output  [511:0] local_buf_57_V_d0;
output  [5:0] local_buf_58_V_address0;
output   local_buf_58_V_ce0;
output   local_buf_58_V_we0;
output  [511:0] local_buf_58_V_d0;
output  [5:0] local_buf_59_V_address0;
output   local_buf_59_V_ce0;
output   local_buf_59_V_we0;
output  [511:0] local_buf_59_V_d0;
output  [5:0] local_buf_60_V_address0;
output   local_buf_60_V_ce0;
output   local_buf_60_V_we0;
output  [511:0] local_buf_60_V_d0;
output  [5:0] local_buf_61_V_address0;
output   local_buf_61_V_ce0;
output   local_buf_61_V_we0;
output  [511:0] local_buf_61_V_d0;
output  [5:0] local_buf_62_V_address0;
output   local_buf_62_V_ce0;
output   local_buf_62_V_we0;
output  [511:0] local_buf_62_V_d0;
output  [5:0] local_buf_63_V_address0;
output   local_buf_63_V_ce0;
output   local_buf_63_V_we0;
output  [511:0] local_buf_63_V_d0;
output   m_axi_global_buf_V_AWVALID;
input   m_axi_global_buf_V_AWREADY;
output  [31:0] m_axi_global_buf_V_AWADDR;
output  [0:0] m_axi_global_buf_V_AWID;
output  [31:0] m_axi_global_buf_V_AWLEN;
output  [2:0] m_axi_global_buf_V_AWSIZE;
output  [1:0] m_axi_global_buf_V_AWBURST;
output  [1:0] m_axi_global_buf_V_AWLOCK;
output  [3:0] m_axi_global_buf_V_AWCACHE;
output  [2:0] m_axi_global_buf_V_AWPROT;
output  [3:0] m_axi_global_buf_V_AWQOS;
output  [3:0] m_axi_global_buf_V_AWREGION;
output  [0:0] m_axi_global_buf_V_AWUSER;
output   m_axi_global_buf_V_WVALID;
input   m_axi_global_buf_V_WREADY;
output  [511:0] m_axi_global_buf_V_WDATA;
output  [63:0] m_axi_global_buf_V_WSTRB;
output   m_axi_global_buf_V_WLAST;
output  [0:0] m_axi_global_buf_V_WID;
output  [0:0] m_axi_global_buf_V_WUSER;
output   m_axi_global_buf_V_ARVALID;
input   m_axi_global_buf_V_ARREADY;
output  [31:0] m_axi_global_buf_V_ARADDR;
output  [0:0] m_axi_global_buf_V_ARID;
output  [31:0] m_axi_global_buf_V_ARLEN;
output  [2:0] m_axi_global_buf_V_ARSIZE;
output  [1:0] m_axi_global_buf_V_ARBURST;
output  [1:0] m_axi_global_buf_V_ARLOCK;
output  [3:0] m_axi_global_buf_V_ARCACHE;
output  [2:0] m_axi_global_buf_V_ARPROT;
output  [3:0] m_axi_global_buf_V_ARQOS;
output  [3:0] m_axi_global_buf_V_ARREGION;
output  [0:0] m_axi_global_buf_V_ARUSER;
input   m_axi_global_buf_V_RVALID;
output   m_axi_global_buf_V_RREADY;
input  [511:0] m_axi_global_buf_V_RDATA;
input   m_axi_global_buf_V_RLAST;
input  [0:0] m_axi_global_buf_V_RID;
input  [0:0] m_axi_global_buf_V_RUSER;
input  [1:0] m_axi_global_buf_V_RRESP;
input   m_axi_global_buf_V_BVALID;
output   m_axi_global_buf_V_BREADY;
input  [1:0] m_axi_global_buf_V_BRESP;
input  [0:0] m_axi_global_buf_V_BID;
input  [0:0] m_axi_global_buf_V_BUSER;
input  [25:0] global_buf_V_offset;
input  [21:0] global_buf_V_offset1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg local_buf_0_V_ce0;
reg local_buf_0_V_we0;
reg local_buf_1_V_ce0;
reg local_buf_1_V_we0;
reg local_buf_2_V_ce0;
reg local_buf_2_V_we0;
reg local_buf_3_V_ce0;
reg local_buf_3_V_we0;
reg local_buf_4_V_ce0;
reg local_buf_4_V_we0;
reg local_buf_5_V_ce0;
reg local_buf_5_V_we0;
reg local_buf_6_V_ce0;
reg local_buf_6_V_we0;
reg local_buf_7_V_ce0;
reg local_buf_7_V_we0;
reg local_buf_8_V_ce0;
reg local_buf_8_V_we0;
reg local_buf_9_V_ce0;
reg local_buf_9_V_we0;
reg local_buf_10_V_ce0;
reg local_buf_10_V_we0;
reg local_buf_11_V_ce0;
reg local_buf_11_V_we0;
reg local_buf_12_V_ce0;
reg local_buf_12_V_we0;
reg local_buf_13_V_ce0;
reg local_buf_13_V_we0;
reg local_buf_14_V_ce0;
reg local_buf_14_V_we0;
reg local_buf_15_V_ce0;
reg local_buf_15_V_we0;
reg local_buf_16_V_ce0;
reg local_buf_16_V_we0;
reg local_buf_17_V_ce0;
reg local_buf_17_V_we0;
reg local_buf_18_V_ce0;
reg local_buf_18_V_we0;
reg local_buf_19_V_ce0;
reg local_buf_19_V_we0;
reg local_buf_20_V_ce0;
reg local_buf_20_V_we0;
reg local_buf_21_V_ce0;
reg local_buf_21_V_we0;
reg local_buf_22_V_ce0;
reg local_buf_22_V_we0;
reg local_buf_23_V_ce0;
reg local_buf_23_V_we0;
reg local_buf_24_V_ce0;
reg local_buf_24_V_we0;
reg local_buf_25_V_ce0;
reg local_buf_25_V_we0;
reg local_buf_26_V_ce0;
reg local_buf_26_V_we0;
reg local_buf_27_V_ce0;
reg local_buf_27_V_we0;
reg local_buf_28_V_ce0;
reg local_buf_28_V_we0;
reg local_buf_29_V_ce0;
reg local_buf_29_V_we0;
reg local_buf_30_V_ce0;
reg local_buf_30_V_we0;
reg local_buf_31_V_ce0;
reg local_buf_31_V_we0;
reg local_buf_32_V_ce0;
reg local_buf_32_V_we0;
reg local_buf_33_V_ce0;
reg local_buf_33_V_we0;
reg local_buf_34_V_ce0;
reg local_buf_34_V_we0;
reg local_buf_35_V_ce0;
reg local_buf_35_V_we0;
reg local_buf_36_V_ce0;
reg local_buf_36_V_we0;
reg local_buf_37_V_ce0;
reg local_buf_37_V_we0;
reg local_buf_38_V_ce0;
reg local_buf_38_V_we0;
reg local_buf_39_V_ce0;
reg local_buf_39_V_we0;
reg local_buf_40_V_ce0;
reg local_buf_40_V_we0;
reg local_buf_41_V_ce0;
reg local_buf_41_V_we0;
reg local_buf_42_V_ce0;
reg local_buf_42_V_we0;
reg local_buf_43_V_ce0;
reg local_buf_43_V_we0;
reg local_buf_44_V_ce0;
reg local_buf_44_V_we0;
reg local_buf_45_V_ce0;
reg local_buf_45_V_we0;
reg local_buf_46_V_ce0;
reg local_buf_46_V_we0;
reg local_buf_47_V_ce0;
reg local_buf_47_V_we0;
reg local_buf_48_V_ce0;
reg local_buf_48_V_we0;
reg local_buf_49_V_ce0;
reg local_buf_49_V_we0;
reg local_buf_50_V_ce0;
reg local_buf_50_V_we0;
reg local_buf_51_V_ce0;
reg local_buf_51_V_we0;
reg local_buf_52_V_ce0;
reg local_buf_52_V_we0;
reg local_buf_53_V_ce0;
reg local_buf_53_V_we0;
reg local_buf_54_V_ce0;
reg local_buf_54_V_we0;
reg local_buf_55_V_ce0;
reg local_buf_55_V_we0;
reg local_buf_56_V_ce0;
reg local_buf_56_V_we0;
reg local_buf_57_V_ce0;
reg local_buf_57_V_we0;
reg local_buf_58_V_ce0;
reg local_buf_58_V_we0;
reg local_buf_59_V_ce0;
reg local_buf_59_V_we0;
reg local_buf_60_V_ce0;
reg local_buf_60_V_we0;
reg local_buf_61_V_ce0;
reg local_buf_61_V_we0;
reg local_buf_62_V_ce0;
reg local_buf_62_V_we0;
reg local_buf_63_V_ce0;
reg local_buf_63_V_we0;
reg m_axi_global_buf_V_ARVALID;
reg m_axi_global_buf_V_RREADY;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    global_buf_V_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    global_buf_V_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_flatten_reg_1411;
reg   [12:0] indvar_flatten_reg_1192;
reg   [6:0] j_reg_1203;
reg   [6:0] indvar_reg_1214;
wire   [0:0] flag_read_read_fu_342_p2;
wire   [26:0] sum_fu_1233_p2;
reg   [26:0] sum_reg_1400;
reg    ap_sig_ioackin_m_axi_global_buf_V_ARREADY;
wire   [0:0] exitcond_flatten_fu_1249_p2;
wire    ap_block_state9_pp0_stage0_iter0;
reg    ap_block_state10_pp0_stage0_iter1;
wire    ap_block_state11_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [12:0] indvar_flatten_next_fu_1255_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [6:0] indvar_mid2_fu_1267_p3;
reg   [6:0] indvar_mid2_reg_1420;
wire   [6:0] tmp_mid2_v_v_fu_1281_p3;
reg   [6:0] tmp_mid2_v_v_reg_1425;
wire   [5:0] tmp_fu_1289_p1;
reg   [5:0] tmp_reg_1430;
wire   [6:0] indvar_next_fu_1293_p2;
wire   [5:0] tmp_63_fu_1299_p1;
reg   [5:0] tmp_63_reg_1440;
reg   [5:0] tmp_63_reg_1440_pp0_iter1_reg;
reg   [511:0] global_buf_V_addr_re_reg_1445;
reg   [5:0] p_t_reg_1513;
wire    ap_CS_fsm_state8;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state9;
reg    ap_enable_reg_pp0_iter2;
reg   [6:0] ap_phi_mux_j_phi_fu_1207_p4;
wire   [63:0] tmp_70_cast_fu_1329_p1;
wire   [63:0] sum_cast_fu_1239_p1;
reg    ap_reg_ioackin_m_axi_global_buf_V_ARREADY;
wire   [26:0] tmp_cast_fu_1225_p1;
wire   [26:0] sext_cast_fu_1229_p1;
wire   [0:0] exitcond_fu_1261_p2;
wire   [6:0] j_s_fu_1275_p2;
wire   [11:0] tmp_mid2_fu_1303_p3;
wire   [11:0] indvar3_cast1_fu_1310_p1;
wire   [11:0] tmp_5_fu_1313_p2;
wire    ap_CS_fsm_state12;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_reg_ioackin_m_axi_global_buf_V_ARREADY = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state9) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state9)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state9);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_m_axi_global_buf_V_ARREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            if ((ap_sig_ioackin_m_axi_global_buf_V_ARREADY == 1'b1)) begin
                ap_reg_ioackin_m_axi_global_buf_V_ARREADY <= 1'b0;
            end else if ((m_axi_global_buf_V_ARREADY == 1'b1)) begin
                ap_reg_ioackin_m_axi_global_buf_V_ARREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_1249_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_1192 <= indvar_flatten_next_fu_1255_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        indvar_flatten_reg_1192 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_1249_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_reg_1214 <= indvar_next_fu_1293_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        indvar_reg_1214 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_reg_1411 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_reg_1203 <= tmp_mid2_v_v_reg_1425;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        j_reg_1203 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_flatten_reg_1411 <= exitcond_flatten_fu_1249_p2;
        tmp_63_reg_1440_pp0_iter1_reg <= tmp_63_reg_1440;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_reg_1411 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        global_buf_V_addr_re_reg_1445 <= m_axi_global_buf_V_RDATA;
        p_t_reg_1513 <= {{tmp_5_fu_1313_p2[11:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_1249_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_mid2_reg_1420 <= indvar_mid2_fu_1267_p3;
        tmp_63_reg_1440 <= tmp_63_fu_1299_p1;
        tmp_reg_1430 <= tmp_fu_1289_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((flag_read_read_fu_342_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sum_reg_1400 <= sum_fu_1233_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_1249_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_mid2_v_v_reg_1425 <= tmp_mid2_v_v_fu_1281_p3;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_1249_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state9 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state9 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond_flatten_reg_1411 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_j_phi_fu_1207_p4 = tmp_mid2_v_v_reg_1425;
    end else begin
        ap_phi_mux_j_phi_fu_1207_p4 = j_reg_1203;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_m_axi_global_buf_V_ARREADY == 1'b0)) begin
        ap_sig_ioackin_m_axi_global_buf_V_ARREADY = m_axi_global_buf_V_ARREADY;
    end else begin
        ap_sig_ioackin_m_axi_global_buf_V_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        global_buf_V_blk_n_AR = m_axi_global_buf_V_ARREADY;
    end else begin
        global_buf_V_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond_flatten_reg_1411 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        global_buf_V_blk_n_R = m_axi_global_buf_V_RVALID;
    end else begin
        global_buf_V_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_0_V_ce0 = 1'b1;
    end else begin
        local_buf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_0_V_we0 = 1'b1;
    end else begin
        local_buf_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_10_V_ce0 = 1'b1;
    end else begin
        local_buf_10_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_10_V_we0 = 1'b1;
    end else begin
        local_buf_10_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_11_V_ce0 = 1'b1;
    end else begin
        local_buf_11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_11_V_we0 = 1'b1;
    end else begin
        local_buf_11_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_12_V_ce0 = 1'b1;
    end else begin
        local_buf_12_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_12_V_we0 = 1'b1;
    end else begin
        local_buf_12_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_13_V_ce0 = 1'b1;
    end else begin
        local_buf_13_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_13_V_we0 = 1'b1;
    end else begin
        local_buf_13_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_14_V_ce0 = 1'b1;
    end else begin
        local_buf_14_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_14_V_we0 = 1'b1;
    end else begin
        local_buf_14_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_15_V_ce0 = 1'b1;
    end else begin
        local_buf_15_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_15_V_we0 = 1'b1;
    end else begin
        local_buf_15_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_16_V_ce0 = 1'b1;
    end else begin
        local_buf_16_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd16) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_16_V_we0 = 1'b1;
    end else begin
        local_buf_16_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_17_V_ce0 = 1'b1;
    end else begin
        local_buf_17_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd17) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_17_V_we0 = 1'b1;
    end else begin
        local_buf_17_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_18_V_ce0 = 1'b1;
    end else begin
        local_buf_18_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd18) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_18_V_we0 = 1'b1;
    end else begin
        local_buf_18_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_19_V_ce0 = 1'b1;
    end else begin
        local_buf_19_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd19) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_19_V_we0 = 1'b1;
    end else begin
        local_buf_19_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_1_V_ce0 = 1'b1;
    end else begin
        local_buf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_1_V_we0 = 1'b1;
    end else begin
        local_buf_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_20_V_ce0 = 1'b1;
    end else begin
        local_buf_20_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd20) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_20_V_we0 = 1'b1;
    end else begin
        local_buf_20_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_21_V_ce0 = 1'b1;
    end else begin
        local_buf_21_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd21) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_21_V_we0 = 1'b1;
    end else begin
        local_buf_21_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_22_V_ce0 = 1'b1;
    end else begin
        local_buf_22_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd22) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_22_V_we0 = 1'b1;
    end else begin
        local_buf_22_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_23_V_ce0 = 1'b1;
    end else begin
        local_buf_23_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd23) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_23_V_we0 = 1'b1;
    end else begin
        local_buf_23_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_24_V_ce0 = 1'b1;
    end else begin
        local_buf_24_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd24) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_24_V_we0 = 1'b1;
    end else begin
        local_buf_24_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_25_V_ce0 = 1'b1;
    end else begin
        local_buf_25_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd25) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_25_V_we0 = 1'b1;
    end else begin
        local_buf_25_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_26_V_ce0 = 1'b1;
    end else begin
        local_buf_26_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd26) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_26_V_we0 = 1'b1;
    end else begin
        local_buf_26_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_27_V_ce0 = 1'b1;
    end else begin
        local_buf_27_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd27) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_27_V_we0 = 1'b1;
    end else begin
        local_buf_27_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_28_V_ce0 = 1'b1;
    end else begin
        local_buf_28_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd28) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_28_V_we0 = 1'b1;
    end else begin
        local_buf_28_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_29_V_ce0 = 1'b1;
    end else begin
        local_buf_29_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd29) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_29_V_we0 = 1'b1;
    end else begin
        local_buf_29_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_2_V_ce0 = 1'b1;
    end else begin
        local_buf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_2_V_we0 = 1'b1;
    end else begin
        local_buf_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_30_V_ce0 = 1'b1;
    end else begin
        local_buf_30_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd30) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_30_V_we0 = 1'b1;
    end else begin
        local_buf_30_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_31_V_ce0 = 1'b1;
    end else begin
        local_buf_31_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd31) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_31_V_we0 = 1'b1;
    end else begin
        local_buf_31_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_32_V_ce0 = 1'b1;
    end else begin
        local_buf_32_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd32) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_32_V_we0 = 1'b1;
    end else begin
        local_buf_32_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_33_V_ce0 = 1'b1;
    end else begin
        local_buf_33_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd33) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_33_V_we0 = 1'b1;
    end else begin
        local_buf_33_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_34_V_ce0 = 1'b1;
    end else begin
        local_buf_34_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd34) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_34_V_we0 = 1'b1;
    end else begin
        local_buf_34_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_35_V_ce0 = 1'b1;
    end else begin
        local_buf_35_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd35) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_35_V_we0 = 1'b1;
    end else begin
        local_buf_35_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_36_V_ce0 = 1'b1;
    end else begin
        local_buf_36_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd36) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_36_V_we0 = 1'b1;
    end else begin
        local_buf_36_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_37_V_ce0 = 1'b1;
    end else begin
        local_buf_37_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd37) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_37_V_we0 = 1'b1;
    end else begin
        local_buf_37_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_38_V_ce0 = 1'b1;
    end else begin
        local_buf_38_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd38) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_38_V_we0 = 1'b1;
    end else begin
        local_buf_38_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_39_V_ce0 = 1'b1;
    end else begin
        local_buf_39_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd39) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_39_V_we0 = 1'b1;
    end else begin
        local_buf_39_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_3_V_ce0 = 1'b1;
    end else begin
        local_buf_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_3_V_we0 = 1'b1;
    end else begin
        local_buf_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_40_V_ce0 = 1'b1;
    end else begin
        local_buf_40_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd40) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_40_V_we0 = 1'b1;
    end else begin
        local_buf_40_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_41_V_ce0 = 1'b1;
    end else begin
        local_buf_41_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd41) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_41_V_we0 = 1'b1;
    end else begin
        local_buf_41_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_42_V_ce0 = 1'b1;
    end else begin
        local_buf_42_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd42) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_42_V_we0 = 1'b1;
    end else begin
        local_buf_42_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_43_V_ce0 = 1'b1;
    end else begin
        local_buf_43_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd43) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_43_V_we0 = 1'b1;
    end else begin
        local_buf_43_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_44_V_ce0 = 1'b1;
    end else begin
        local_buf_44_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd44) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_44_V_we0 = 1'b1;
    end else begin
        local_buf_44_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_45_V_ce0 = 1'b1;
    end else begin
        local_buf_45_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd45) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_45_V_we0 = 1'b1;
    end else begin
        local_buf_45_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_46_V_ce0 = 1'b1;
    end else begin
        local_buf_46_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd46) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_46_V_we0 = 1'b1;
    end else begin
        local_buf_46_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_47_V_ce0 = 1'b1;
    end else begin
        local_buf_47_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd47) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_47_V_we0 = 1'b1;
    end else begin
        local_buf_47_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_48_V_ce0 = 1'b1;
    end else begin
        local_buf_48_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd48) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_48_V_we0 = 1'b1;
    end else begin
        local_buf_48_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_49_V_ce0 = 1'b1;
    end else begin
        local_buf_49_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd49) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_49_V_we0 = 1'b1;
    end else begin
        local_buf_49_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_4_V_ce0 = 1'b1;
    end else begin
        local_buf_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_4_V_we0 = 1'b1;
    end else begin
        local_buf_4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_50_V_ce0 = 1'b1;
    end else begin
        local_buf_50_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd50) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_50_V_we0 = 1'b1;
    end else begin
        local_buf_50_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_51_V_ce0 = 1'b1;
    end else begin
        local_buf_51_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd51) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_51_V_we0 = 1'b1;
    end else begin
        local_buf_51_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_52_V_ce0 = 1'b1;
    end else begin
        local_buf_52_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd52) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_52_V_we0 = 1'b1;
    end else begin
        local_buf_52_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_53_V_ce0 = 1'b1;
    end else begin
        local_buf_53_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd53) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_53_V_we0 = 1'b1;
    end else begin
        local_buf_53_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_54_V_ce0 = 1'b1;
    end else begin
        local_buf_54_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd54) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_54_V_we0 = 1'b1;
    end else begin
        local_buf_54_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_55_V_ce0 = 1'b1;
    end else begin
        local_buf_55_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd55) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_55_V_we0 = 1'b1;
    end else begin
        local_buf_55_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_56_V_ce0 = 1'b1;
    end else begin
        local_buf_56_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd56) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_56_V_we0 = 1'b1;
    end else begin
        local_buf_56_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_57_V_ce0 = 1'b1;
    end else begin
        local_buf_57_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd57) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_57_V_we0 = 1'b1;
    end else begin
        local_buf_57_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_58_V_ce0 = 1'b1;
    end else begin
        local_buf_58_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd58) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_58_V_we0 = 1'b1;
    end else begin
        local_buf_58_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_59_V_ce0 = 1'b1;
    end else begin
        local_buf_59_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd59) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_59_V_we0 = 1'b1;
    end else begin
        local_buf_59_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_5_V_ce0 = 1'b1;
    end else begin
        local_buf_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_5_V_we0 = 1'b1;
    end else begin
        local_buf_5_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_60_V_ce0 = 1'b1;
    end else begin
        local_buf_60_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd60) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_60_V_we0 = 1'b1;
    end else begin
        local_buf_60_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_61_V_ce0 = 1'b1;
    end else begin
        local_buf_61_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd61) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_61_V_we0 = 1'b1;
    end else begin
        local_buf_61_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_62_V_ce0 = 1'b1;
    end else begin
        local_buf_62_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd62) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_62_V_we0 = 1'b1;
    end else begin
        local_buf_62_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_63_V_ce0 = 1'b1;
    end else begin
        local_buf_63_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd63) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_63_V_we0 = 1'b1;
    end else begin
        local_buf_63_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_6_V_ce0 = 1'b1;
    end else begin
        local_buf_6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_6_V_we0 = 1'b1;
    end else begin
        local_buf_6_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_7_V_ce0 = 1'b1;
    end else begin
        local_buf_7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_7_V_we0 = 1'b1;
    end else begin
        local_buf_7_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_8_V_ce0 = 1'b1;
    end else begin
        local_buf_8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_8_V_we0 = 1'b1;
    end else begin
        local_buf_8_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_9_V_ce0 = 1'b1;
    end else begin
        local_buf_9_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_t_reg_1513 == 6'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_buf_9_V_we0 = 1'b1;
    end else begin
        local_buf_9_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_m_axi_global_buf_V_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_global_buf_V_ARVALID = 1'b1;
    end else begin
        m_axi_global_buf_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_reg_1411 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_global_buf_V_RREADY = 1'b1;
    end else begin
        m_axi_global_buf_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((flag_read_read_fu_342_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((flag_read_read_fu_342_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((ap_sig_ioackin_m_axi_global_buf_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (exitcond_flatten_fu_1249_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (exitcond_flatten_fu_1249_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((exitcond_flatten_reg_1411 == 1'd0) & (m_axi_global_buf_V_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((exitcond_flatten_reg_1411 == 1'd0) & (m_axi_global_buf_V_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter1 = ((exitcond_flatten_reg_1411 == 1'd0) & (m_axi_global_buf_V_RVALID == 1'b0));
end

assign ap_block_state11_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond_flatten_fu_1249_p2 = ((indvar_flatten_reg_1192 == 13'd4096) ? 1'b1 : 1'b0);

assign exitcond_fu_1261_p2 = ((indvar_reg_1214 == 7'd64) ? 1'b1 : 1'b0);

assign flag_read_read_fu_342_p2 = flag;

assign indvar3_cast1_fu_1310_p1 = indvar_mid2_reg_1420;

assign indvar_flatten_next_fu_1255_p2 = (indvar_flatten_reg_1192 + 13'd1);

assign indvar_mid2_fu_1267_p3 = ((exitcond_fu_1261_p2[0:0] === 1'b1) ? 7'd0 : indvar_reg_1214);

assign indvar_next_fu_1293_p2 = (7'd1 + indvar_mid2_fu_1267_p3);

assign j_s_fu_1275_p2 = (7'd1 + ap_phi_mux_j_phi_fu_1207_p4);

assign local_buf_0_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_0_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_10_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_10_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_11_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_11_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_12_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_12_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_13_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_13_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_14_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_14_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_15_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_15_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_16_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_16_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_17_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_17_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_18_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_18_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_19_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_19_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_1_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_1_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_20_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_20_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_21_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_21_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_22_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_22_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_23_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_23_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_24_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_24_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_25_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_25_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_26_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_26_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_27_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_27_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_28_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_28_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_29_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_29_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_2_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_2_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_30_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_30_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_31_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_31_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_32_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_32_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_33_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_33_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_34_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_34_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_35_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_35_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_36_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_36_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_37_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_37_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_38_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_38_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_39_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_39_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_3_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_3_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_40_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_40_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_41_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_41_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_42_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_42_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_43_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_43_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_44_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_44_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_45_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_45_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_46_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_46_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_47_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_47_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_48_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_48_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_49_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_49_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_4_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_4_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_50_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_50_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_51_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_51_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_52_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_52_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_53_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_53_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_54_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_54_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_55_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_55_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_56_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_56_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_57_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_57_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_58_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_58_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_59_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_59_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_5_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_5_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_60_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_60_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_61_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_61_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_62_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_62_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_63_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_63_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_6_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_6_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_7_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_7_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_8_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_8_V_d0 = global_buf_V_addr_re_reg_1445;

assign local_buf_9_V_address0 = tmp_70_cast_fu_1329_p1;

assign local_buf_9_V_d0 = global_buf_V_addr_re_reg_1445;

assign m_axi_global_buf_V_ARADDR = sum_cast_fu_1239_p1;

assign m_axi_global_buf_V_ARBURST = 2'd0;

assign m_axi_global_buf_V_ARCACHE = 4'd0;

assign m_axi_global_buf_V_ARID = 1'd0;

assign m_axi_global_buf_V_ARLEN = 32'd4096;

assign m_axi_global_buf_V_ARLOCK = 2'd0;

assign m_axi_global_buf_V_ARPROT = 3'd0;

assign m_axi_global_buf_V_ARQOS = 4'd0;

assign m_axi_global_buf_V_ARREGION = 4'd0;

assign m_axi_global_buf_V_ARSIZE = 3'd0;

assign m_axi_global_buf_V_ARUSER = 1'd0;

assign m_axi_global_buf_V_AWADDR = 32'd0;

assign m_axi_global_buf_V_AWBURST = 2'd0;

assign m_axi_global_buf_V_AWCACHE = 4'd0;

assign m_axi_global_buf_V_AWID = 1'd0;

assign m_axi_global_buf_V_AWLEN = 32'd0;

assign m_axi_global_buf_V_AWLOCK = 2'd0;

assign m_axi_global_buf_V_AWPROT = 3'd0;

assign m_axi_global_buf_V_AWQOS = 4'd0;

assign m_axi_global_buf_V_AWREGION = 4'd0;

assign m_axi_global_buf_V_AWSIZE = 3'd0;

assign m_axi_global_buf_V_AWUSER = 1'd0;

assign m_axi_global_buf_V_AWVALID = 1'b0;

assign m_axi_global_buf_V_BREADY = 1'b0;

assign m_axi_global_buf_V_WDATA = 512'd0;

assign m_axi_global_buf_V_WID = 1'd0;

assign m_axi_global_buf_V_WLAST = 1'b0;

assign m_axi_global_buf_V_WSTRB = 64'd0;

assign m_axi_global_buf_V_WUSER = 1'd0;

assign m_axi_global_buf_V_WVALID = 1'b0;

assign sext_cast_fu_1229_p1 = global_buf_V_offset;

assign sum_cast_fu_1239_p1 = sum_reg_1400;

assign sum_fu_1233_p2 = (tmp_cast_fu_1225_p1 + sext_cast_fu_1229_p1);

assign tmp_5_fu_1313_p2 = (tmp_mid2_fu_1303_p3 + indvar3_cast1_fu_1310_p1);

assign tmp_63_fu_1299_p1 = indvar_mid2_fu_1267_p3[5:0];

assign tmp_70_cast_fu_1329_p1 = tmp_63_reg_1440_pp0_iter1_reg;

assign tmp_cast_fu_1225_p1 = global_buf_V_offset1;

assign tmp_fu_1289_p1 = tmp_mid2_v_v_fu_1281_p3[5:0];

assign tmp_mid2_fu_1303_p3 = {{tmp_reg_1430}, {6'd0}};

assign tmp_mid2_v_v_fu_1281_p3 = ((exitcond_fu_1261_p2[0:0] === 1'b1) ? j_s_fu_1275_p2 : ap_phi_mux_j_phi_fu_1207_p4);

endmodule //buffer_load
