// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _jacobi2d_kernel_jacobi2d_kernel_entry118311_HH_
#define _jacobi2d_kernel_jacobi2d_kernel_entry118311_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct jacobi2d_kernel_jacobi2d_kernel_entry118311 : public sc_module {
    // Port declarations 55
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<64> > coalesced_data_num;
    sc_out< sc_lv<64> > coalesced_data_num_out_din;
    sc_in< sc_logic > coalesced_data_num_out_full_n;
    sc_out< sc_logic > coalesced_data_num_out_write;
    sc_out< sc_lv<64> > coalesced_data_num_out1_din;
    sc_in< sc_logic > coalesced_data_num_out1_full_n;
    sc_out< sc_logic > coalesced_data_num_out1_write;
    sc_out< sc_lv<64> > coalesced_data_num_out2_din;
    sc_in< sc_logic > coalesced_data_num_out2_full_n;
    sc_out< sc_logic > coalesced_data_num_out2_write;
    sc_out< sc_lv<64> > coalesced_data_num_out3_din;
    sc_in< sc_logic > coalesced_data_num_out3_full_n;
    sc_out< sc_logic > coalesced_data_num_out3_write;
    sc_in< sc_lv<32> > var_output_0_0_V;
    sc_in< sc_lv<32> > var_output_0_1_V;
    sc_in< sc_lv<32> > var_output_0_2_V;
    sc_in< sc_lv<32> > var_output_0_3_V;
    sc_in< sc_lv<32> > var_input_0_0_V;
    sc_in< sc_lv<32> > var_input_0_1_V;
    sc_in< sc_lv<32> > var_input_0_2_V;
    sc_in< sc_lv<32> > var_input_0_3_V;
    sc_out< sc_lv<32> > var_output_0_0_V_out_din;
    sc_in< sc_logic > var_output_0_0_V_out_full_n;
    sc_out< sc_logic > var_output_0_0_V_out_write;
    sc_out< sc_lv<32> > var_output_0_1_V_out_din;
    sc_in< sc_logic > var_output_0_1_V_out_full_n;
    sc_out< sc_logic > var_output_0_1_V_out_write;
    sc_out< sc_lv<32> > var_output_0_2_V_out_din;
    sc_in< sc_logic > var_output_0_2_V_out_full_n;
    sc_out< sc_logic > var_output_0_2_V_out_write;
    sc_out< sc_lv<32> > var_output_0_3_V_out_din;
    sc_in< sc_logic > var_output_0_3_V_out_full_n;
    sc_out< sc_logic > var_output_0_3_V_out_write;
    sc_out< sc_lv<32> > var_input_0_0_V_out_din;
    sc_in< sc_logic > var_input_0_0_V_out_full_n;
    sc_out< sc_logic > var_input_0_0_V_out_write;
    sc_out< sc_lv<32> > var_input_0_1_V_out_din;
    sc_in< sc_logic > var_input_0_1_V_out_full_n;
    sc_out< sc_logic > var_input_0_1_V_out_write;
    sc_out< sc_lv<32> > var_input_0_2_V_out_din;
    sc_in< sc_logic > var_input_0_2_V_out_full_n;
    sc_out< sc_logic > var_input_0_2_V_out_write;
    sc_out< sc_lv<32> > var_input_0_3_V_out_din;
    sc_in< sc_logic > var_input_0_3_V_out_full_n;
    sc_out< sc_logic > var_input_0_3_V_out_write;


    // Module declarations
    jacobi2d_kernel_jacobi2d_kernel_entry118311(sc_module_name name);
    SC_HAS_PROCESS(jacobi2d_kernel_jacobi2d_kernel_entry118311);

    ~jacobi2d_kernel_jacobi2d_kernel_entry118311();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > coalesced_data_num_out_blk_n;
    sc_signal< sc_logic > coalesced_data_num_out1_blk_n;
    sc_signal< sc_logic > coalesced_data_num_out2_blk_n;
    sc_signal< sc_logic > coalesced_data_num_out3_blk_n;
    sc_signal< sc_logic > var_output_0_0_V_out_blk_n;
    sc_signal< sc_logic > var_output_0_1_V_out_blk_n;
    sc_signal< sc_logic > var_output_0_2_V_out_blk_n;
    sc_signal< sc_logic > var_output_0_3_V_out_blk_n;
    sc_signal< sc_logic > var_input_0_0_V_out_blk_n;
    sc_signal< sc_logic > var_input_0_1_V_out_blk_n;
    sc_signal< sc_logic > var_input_0_2_V_out_blk_n;
    sc_signal< sc_logic > var_input_0_3_V_out_blk_n;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_coalesced_data_num_out1_blk_n();
    void thread_coalesced_data_num_out1_din();
    void thread_coalesced_data_num_out1_write();
    void thread_coalesced_data_num_out2_blk_n();
    void thread_coalesced_data_num_out2_din();
    void thread_coalesced_data_num_out2_write();
    void thread_coalesced_data_num_out3_blk_n();
    void thread_coalesced_data_num_out3_din();
    void thread_coalesced_data_num_out3_write();
    void thread_coalesced_data_num_out_blk_n();
    void thread_coalesced_data_num_out_din();
    void thread_coalesced_data_num_out_write();
    void thread_internal_ap_ready();
    void thread_real_start();
    void thread_start_out();
    void thread_start_write();
    void thread_var_input_0_0_V_out_blk_n();
    void thread_var_input_0_0_V_out_din();
    void thread_var_input_0_0_V_out_write();
    void thread_var_input_0_1_V_out_blk_n();
    void thread_var_input_0_1_V_out_din();
    void thread_var_input_0_1_V_out_write();
    void thread_var_input_0_2_V_out_blk_n();
    void thread_var_input_0_2_V_out_din();
    void thread_var_input_0_2_V_out_write();
    void thread_var_input_0_3_V_out_blk_n();
    void thread_var_input_0_3_V_out_din();
    void thread_var_input_0_3_V_out_write();
    void thread_var_output_0_0_V_out_blk_n();
    void thread_var_output_0_0_V_out_din();
    void thread_var_output_0_0_V_out_write();
    void thread_var_output_0_1_V_out_blk_n();
    void thread_var_output_0_1_V_out_din();
    void thread_var_output_0_1_V_out_write();
    void thread_var_output_0_2_V_out_blk_n();
    void thread_var_output_0_2_V_out_din();
    void thread_var_output_0_2_V_out_write();
    void thread_var_output_0_3_V_out_blk_n();
    void thread_var_output_0_3_V_out_din();
    void thread_var_output_0_3_V_out_write();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
